# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 929302ec2f2c2b132e35d253813f5498bbd9f906c99f7270a240f61db0dfa6ee43319386df03fa36fc1996858b16e0604ca7dc47987b81155668c519dd95d0bd

test:
  secret_key_base: d0b66ccf84598d68c6d81f23a3cb93747a418b0cd713208babcafc9e288f341521324d2bf4ac751d3154e6d725cb7848c74e2c88d6d29a4a2a60a6557b85ece3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
