# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 187c084d939371819d8c651c1120aaf471f6e1964046ea5d089f6f0da2d5e12b0dc7a65a299f174d0f94f3f31ec7a9dc80772505601d0f483fd7b1bb0fbf3e6d

test:
  secret_key_base: 5aa668a4db4470c78cbab170a7e8b01acb0f27bc6aeacbbba27a7a43f8d5e4355613c8624f987b470f467319f85740e2a7c5f351302aca956e3263139ed08366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
