# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 449217b67d14d9027a04be713bb6c74d937ad42b5d64b2cc40cfa0d64fa61ce5b8a1fa6a64a2cdbf247240af81a318742982c558e15b65bed1c350b7767215ef

test:
  secret_key_base: 053abae4240db5cf2e554142185da686a607d011cfbc419eb36adccc269f4d62acecf22f325644fd726c1fdf887d5938a3bb879785a13fba303aa6e3308456dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
