# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16e190eb770678362f9cdeb81adf39037ba3f94cf4bfd8e45611a36878bef9858b0974ab111b5d87b327db954fd21b246002b6cbf9eb63add28528ac919f6bd1

test:
  secret_key_base: 3dc8a61a62fab66ab8bfcbcff36aaad59157b48d7280e9be1f5a58598c1e6bfa98a7a697994974f7e56f596bba789e1e372f42e833c9e725afcac7e3363e4a78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
